### ISSUE TITLE
Struggling to run "npm run serve"

### ISSUE THREAD

**Issue by hynet-mel** [pixeldesu/videoline#43]
<details>
  <summary>npm run serve output</summary>
`
> videoline@0.11.0 serve /tmp/videoline
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

ERROR  Failed to compile with 1 errors

 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /tmp/videoline/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/videoline/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/videoline/node_modules/@babel/preset-env/lib/index.js:11:14)

 @ multi (webpack)-dev-server/client?http://192.168.0.192:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
`
</details>

Honestly, as someone who hasn't messed around with Vue alot. I am struggling to find out where this error is coming from. Does this have to do with my installed version of npm? I am on Debian 10.
I was messing around with running this application in a Docker image (was gonna PR it once it's done) but it fails to build if I follow the instructions on the README.md, both in the host and different node containers.

**Comment by pixeldesu** [comment]
Hmm, I'll check up on this and report back if I can replicate these issues!

**Comment by pixeldesu** [comment]
@hynet-mel I was able to replicate those issues, but fixed them just now. There's a new commit in the `develop` branch addressing the issues. `npm run serve` should now work without any error messages.

You'll probably need to remove your `node_modules` folder in the project once and re-run `npm install`.

If there's any other issue with starting the task, feel free to report them here, otherwise you are free to just close the issue!

**Comment by hynet-mel** [comment]
@pixeldesu Ah! Great, it works just fine now both on the host and on docker! Opened a PR to propose Docker support as well
